# Generated by Django 3.2.23 on 2023-11-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
